### ISSUE TITLE
Problem with Stats API.

### ISSUE THREAD

**Issue by MasterDeflate** [webchain-network/webchain-pool#8]
Stats API Temporarily Down
Usually it's just a temporal issue and mining is not affected.
I tried all ways to fix this i was not possible, i have already a config in nginx.conf about upstream but nothing.
Also i would like to ask why when i ./build.sh the dist i get this:

```
./build.sh
DEPRECATION: Overriding init without calling this._super is deprecated. Please c                                                                                                                                                              all `this._super.init && this._super.init.apply(this, arguments);` addon: `relea                                                                                                                                                              se`
    at addons.forEach.addon (/root/webchain-pool/www/node_modules/ember-cli/lib/                                                                                                                                                              models/project.js:502:40)
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
DEPRECATION: Addon files were detected in `/root/webchain-pool/www/node_modules/                                                                                                                                                              ember-load-initializers/addon`, but no JavaScript preprocessors were found for `                                                                                                                                                              ember-load-initializers`. Please make sure to add a preprocessor (most likely `e                                                                                                                                                              mber-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-load-ini                                                                                                                                                              tializers`'s `package.json`.
WARNING: Invalid Broccoli2 node detected, falling back to broccoli-builder. Broc                                                                                                                                                              coli error:
---------------
Object: The .read/.rebuild API is no longer supported as of Broccoli 1.0. Plugin                                                                                                                                                              s must now derive from broccoli-plugin. https://github.com/broccolijs/broccoli/b                                                                                                                                                              lob/master/docs/broccoli-1-0-plugin-api.md
used as input node to BroccoliMergeTrees (TreeMerger (vendor))
-~- created here: -~-
    at BroccoliMergeTrees.Plugin (/root/webchain-pool/www/node_modules/broccoli-                                                                                                                                                              plugin/index.js:7:31)
    at new BroccoliMergeTrees (/root/webchain-pool/www/node_modules/ember-cli/no                                                                                                                                                              de_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/root/webchain-pool                                                                                                                                                              /www/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/root/webchain-pool/www/node_modules/ember-cli/lib/broccoli/m                                                                                                                                                              erge-trees.js:85:33)
    at EmberApp.getExternalTree (/root/webchain-pool/www/node_modules/ember-cli/                                                                                                                                                              lib/broccoli/ember-app.js:1260:56)
    at EmberApp.toArray (/root/webchain-pool/www/node_modules/ember-cli/lib/broc                                                                                                                                                              coli/ember-app.js:1620:12)
    at EmberApp.toTree (/root/webchain-pool/www/node_modules/ember-cli/lib/brocc                                                                                                                                                              oli/ember-app.js:1750:36)
    at module.exports (/root/webchain-pool/www/ember-cli-build.js:35:14)
    at Builder.readBuildFile (/root/webchain-pool/www/node_modules/ember-cli/lib                                                                                                                                                              /models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/root/webchain-pool/www/node_modules/ember-                                                                                                                                                              cli/lib/models/builder.js:66:22)
-~- (end) -~----------------

Environment: production
[API] Warning: The .read and .rebuild APIs will stop working in the next Broccol                                                                                                                                                              i version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/brocco                                                                                                                                                              li-plugin
[API] Warning: Plugin uses .read/.rebuild API: [object Object]
[API] Warning: Plugin uses .read/.rebuild API: [object Object]
WARN: Output exceeds 32000 characters
cleaning up...
Built project successfully. Stored in "dist/".
File sizes:
 - dist//assets/auto-import-fastboot-d41d8cd98f00b204e9800998ecf8427e.js: 0 B
 - dist//assets/intl/intl-96aafc0a691d5c865ba1bdd814a927c6.js: 40.33 KB (13.51 KB gzipped)
 - dist//assets/intl/intl.complete-19a71cdd590a2cc9a64729029951b2fe.js: 913.18 KB (187.47 KB gzipped)
 - dist//assets/intl/intl.min-a638f49c244882a17fe483d105d5ff57.js: 40.34 KB (13.52 KB gzipped)
 - dist//assets/intl/locales/en-us-f0c5d465ba90e2edd44f76df823a4f02.js: 25.34 KB (3.96 KB gzipped)
 - dist//assets/pool-4087f914df2f048b8e379b91fb118b06.js: 129.47 KB (13.85 KB gzipped)
 - dist//assets/pool-a1c90bfa261a9b88260d3936a503a771.css: 2.53 KB (772 B gzipped)
 - dist//assets/vendor-32d26b8a8f088dab36e418303a207fd4.js: 650.34 KB (173.11 KB gzipped)
 - dist//assets/vendor-d9ddca88ebb00e8e29c83cd8e16d3530.css: 140.78 KB (25.23 KB gzipped)
```

```
root@wechain:~/webchain-pool/www# ember server --port 8082 --environment development
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `release`
    at addons.forEach.addon (/root/webchain-pool/www/node_modules/ember-cli/lib/models/project.js:502:40)
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
DEPRECATION: Addon files were detected in `/root/webchain-pool/www/node_modules/ember-load-initializers/addon`, but no JavaScript preprocessors were found for `ember-load-initializers`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-load-initializers`'s `package.json`.
WARNING: Invalid Broccoli2 node detected, falling back to broccoli-builder. Broccoli error:
---------------
Object: The .read/.rebuild API is no longer supported as of Broccoli 1.0. Plugins must now derive from broccoli-plugin. https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md
used as input node to BroccoliMergeTrees (TreeMerger (vendor))
-~- created here: -~-
    at BroccoliMergeTrees.Plugin (/root/webchain-pool/www/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/root/webchain-pool/www/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/root/webchain-pool/www/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/root/webchain-pool/www/node_modules/ember-cli/lib/broccoli/merge-trees.js:85:33)
    at EmberApp.getExternalTree (/root/webchain-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1260:56)
    at EmberApp.toArray (/root/webchain-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1620:12)
    at EmberApp.toTree (/root/webchain-pool/www/node_modules/ember-cli/lib/broccoli/ember-app.js:1750:36)
    at module.exports (/root/webchain-pool/www/ember-cli-build.js:35:14)
    at Builder.readBuildFile (/root/webchain-pool/www/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/root/webchain-pool/www/node_modules/ember-cli/lib/models/builder.js:66:22)
-~- (end) -~----------------

[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: [object Object]
[API] Warning: Plugin uses .read/.rebuild API: [object Object]

Build successful (2154ms) – Serving on http://localhost:8082/



Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel: pool (2)                               | 644ms (322 ms)
Bundler (1)                                   | 442ms
ember-auto-import-analyzer (3)                | 318ms (106 ms)
Babel: ember-intl (2)                         | 166ms (83 ms)
Package /assets/vendor.js (1)                 | 119ms
```

**Comment by MasterDeflate** [comment]
I fixed the API stats down, but now i have BIG problem, it show at Miners who are connected, but when i try to lookup the address of the miner, it show blank page and redirect example to web.com/#/account/01230x120x0 but blank? Can someone help me fix this issue?

**Comment by lukaszmatczak** [comment]
How have you configured it? As i see you've tried to use "ember server". It's not correct way. You need to serve pool's web panel via nginx. And please write me your node version.

**Comment by MasterDeflate** [comment]
Yea i configured, i message you at discord.

**Comment by lukaszmatczak** [comment]
Answered.

**Comment by MasterDeflate** [comment]
Okay anyway im waiting you at discord i have some problem with pool.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
